E
======================================================================
ERROR: test_training_loop (tests.test_training.TestTrainFunction.test_training_loop)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/unittest/mock.py", line 1372, in patched
    with self.decoration_helper(patched,
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/unittest/mock.py", line 1354, in decoration_helper
    arg = exit_stack.enter_context(patching)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/contextlib.py", line 505, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/unittest/mock.py", line 1539, in __enter__
    new = create_autospec(autospec, spec_set=spec_set,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/unittest/mock.py", line 2720, in create_autospec
    mock = Klass(parent=_parent, _new_parent=_parent, _new_name=_new_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/unittest/mock.py", line 2106, in __init__
    _safe_super(MagicMixin, self).__init__(*args, **kw)
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/unittest/mock.py", line 457, in __init__
    self._mock_add_spec(spec, spec_set, _spec_as_instance, _eat_self)
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/unittest/mock.py", line 515, in _mock_add_spec
    if iscoroutinefunction(getattr(spec, attr, None)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/asyncio/coroutines.py", line 24, in iscoroutinefunction
    getattr(func, '_is_coroutine', None) is _is_coroutine)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/wandb/sdk/lib/lazyloader.py", line 58, in __getattr__
    module = self._load()
             ^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/wandb/sdk/lib/lazyloader.py", line 33, in _load
    module = importlib.import_module(self.__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/wandb/integration/catboost/__init__.py", line 3, in <module>
    from .catboost import WandbCallback, log_summary
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/wandb/integration/catboost/catboost.py", line 7, in <module>
    from catboost import CatBoostClassifier, CatBoostRegressor  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'catboost'
----------------------------------------------------------------------
Ran 1 test in 0.005s
FAILED (errors=1)