Usage: python -m unittest.python -m unittest [OPTIONS]
Try 'python -m unittest.python -m unittest --help' for help.
Error: Got unexpected extra argument (tests.test_training)
E
======================================================================
ERROR: test_training_loop (tests.test_training.TestTrainFunction.test_training_loop)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/click/core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/click/core.py", line 1411, in parse_args
    ctx.fail(
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/click/core.py", line 684, in fail
    raise UsageError(message, self)
click.exceptions.UsageError: Got unexpected extra argument (tests.test_training)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/bencekern/Documents/Sulis cuccok/DTU mester/second_semester/MLOps/mnist_project/tests/test_training.py", line 21, in test_training_loop
    train()
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/click/core.py", line 1096, in main
    sys.exit(e.exit_code)
  File "/Users/bencekern/opt/anaconda3/envs/my_environment/lib/python3.11/site-packages/wandb/sdk/lib/exit_hooks.py", line 36, in exit
    self._orig_exit(orig_code)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemExit: 2
----------------------------------------------------------------------
Ran 1 test in 0.005s
FAILED (errors=1)